apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fluent-bit.fullname" . }}-es-tls-secret"
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ template "fluent-bit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  es-tls-ca.crt: {{ .Values.backend.es.tls_ca | b64enc | quote }}
