{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ template "fluent-bit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fluent-bit.serviceAccountName" . }}
{{- end -}}
